# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Sirity Theme"
license = "MIT"
licenselink = "https://github.com/foreversmart/hugo-sirity-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/foreversmart/hugo-sirity-theme"
tags = ["Blog", "Responsive"]
features = ["", ""]
min_version = 1.0

[author]
  name = "rorschach"
  homepage = "https://github.com/foreversmart/hugo-sirity-theme"
